# Generated by Django 5.2.3 on 2025-06-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeT', '0002_plaidaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
