# Generated by Django 5.2.3 on 2025-06-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeT', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='available_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='mask',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='item_id',
            field=models.CharField(max_length=255),
        ),
    ]
